[project]
name = "2-gemini"
version = "0.1.0"
description = "Sample project to demonstrate usage of Gemini with Langchain."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.0.3",
    "langchain-google-genai>=3.0.0",
    "python-dotenv>=1.2.1",
]
